image: maven:3.8.6-openjdk-11

stages:
  - build
  - test
  - deploy

# Étape de build
build:
  stage: build
  script:
    - mvn clean package

# Étape de test
test:
  stage: test
  script:
    - mvn test

# Étape de déploiement sur Docker Hub
deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE: tchofo/simple-maven-app 
  before_script:
    - echo "Logging into Docker Hub..."
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - main
